### PR TITLE
Internal: Use correct this_ when checking for open context menu

### PR DESCRIPTION
**Pull request by alex-Hudson**
Hi, 
So so sorry but in the previous pull request I refered to the wrong this (this rather than this_)

### CODE REVIEW

**Comment by jonataswalker** [comment]
Hi @alex-Hudson could you please resolve the conficts?

**Comment by alex-Hudson** [comment]
Sorry I’m not sure how to do that on guthub?

**Comment by jonataswalker** [comment]
```
$ git fetch origin master
$ git merge origin/master
```
Open `src/internal.js` and choose the correct code.

**Comment by alex-Hudson** [comment]
Hi @jonataswalker, I've sorted those conflicts. For some reason this check isnt working. Do you think you could take a look?

**Comment by alex-Hudson** [comment]
Hi @jonataswalker, we'd love to use this in our app - is there any way you could please take a look at this?

**Comment by jonataswalker** [comment]
Sorry the delay, will publish today a new version.

**Pull request merged**
