### PR TITLE
Fixed two issues and re-added 'open' event

### PR DESCRIPTION
**Pull request by GastonZalba**
Hi, i made some minor fixes:
- Fixed issue #236 moving the emitter to the setMap method and using `emitter.off` to desubscribe the problematic events.
- Fixed typescript errors on events, referenced on issue #233 
- Added `originalEvent` attribute on the mouse events
- Re-added the `open` event that was missing after commit https://github.com/jonataswalker/ol-contextmenu/commit/f1608b299b386ec7ede47fb7afa86144d3c4e91d (but still included in the documentation)

Let me know if changes are required, hope it helps.

### CODE REVIEW

**Comment by jonataswalker** [comment]
@GastonZalba many thanks for this work, I had an accident and this is the reason for this delay.

**Comment by jonataswalker** [comment]
I will (probably) make some changes to continue returning `pixel` and `coordinate` on events.

**Review by jonataswalker — APPROVED** [review]

**Comment by GastonZalba** [comment]
> I will (probably) make some changes to continue returning `pixel` and `coordinate` on events.

@jonataswalker they are still returning! The `ContextMenuEvent` now extends the ol class [MapBrowserEvent](https://openlayers.org/en/latest/apidoc/module-ol_MapBrowserEvent-MapBrowserEvent.html), which already calculates and returns pixel and coordinates values.

**Comment by jonataswalker** [comment]
Yeah haha, realized right now

**Pull request merged**
